COPY = {
    "fr": {
        "title": "File des pitchs", "subtitle": "Réception, tri et revue des dossiers entrants",
        "disclaimer": "Aide au tri uniquement. Le score et la sélection ne remplacent pas la revue d'un investisseur.",
        "language": "Langue de l’interface", "queue": "File VC", "submit": "Déposer un pitch",
        "all": "Tous les secteurs", "sector": "Secteur", "search": "Rechercher un nom ou un identifiant",
        "received": "Dossiers reçus", "scored": "Scorés", "review_count": "Revue humaine", "pending_count": "En attente",
        "priority": "À examiner", "ranking": "Classement complet", "review": "Revue humaine", "pending": "Sans score",
        "empty_scored": "Aucun score V2 local enregistré. Dépose un pitch ou lance le passage du moteur pour alimenter la file.",
        "empty_selected": "Aucun dossier sélectionnable dans cette vue.",
        "empty_review": "Aucun dossier signalé dans cette vue.",
        "empty_pending": "Tous les dossiers visibles ont un score exploitable.",
        "partial": "La sélection porte sur les dossiers scorés visibles ; elle évoluera quand les autres dossiers seront traités.",
        "company": "Entreprise", "score": "Score / 100", "recommendation": "Avis du modèle",
        "channel": "Canal", "status": "État", "detail": "Fiche détaillée", "choose": "Choisir un dossier",
        "criterion": "Critère", "corpus": "Corpus", "manual": "Dépôt manuel",
        "reject": "Rejeter", "review_rec": "À revoir", "shortlist": "Présélectionner",
        "criteria": "Notes par critère", "strengths": "Forces", "risks": "Risques", "missing": "Informations manquantes",
        "evidence": "Extraits justificatifs", "text": "Texte du pitch", "no_score": "Aucune analyse du modèle pour ce dossier.",
        "guard": "Ce dossier est écarté du classement automatique et doit être relu par un humain.",
        "error": "Dernière tentative de scoring :", "source_language": "Les commentaires du modèle sont affichés dans la langue de leur exécution.",
        "manual_intro": "Saisis un message, ajoute des PDF ou des liens publics. Le texte extrait est envoyé au modèle local après contrôle.",
        "name": "Nom de l’entreprise", "sector_input": "Secteur", "message": "Texte du message ou du pitch",
        "files": "PDF joints", "links": "Liens publics (un par ligne)", "evaluate": "Extraire et noter avec le modèle local",
        "processing": "Extraction et scoring local en cours…", "too_short": "Le texte extrait est trop court pour être noté (minimum 40 mots).",
        "saved": "Dossier enregistré et scoré.", "scoring_failed": "Dossier enregistré, mais le modèle n’a pas produit de score exploitable.",
        "source_report": "Sources lues", "waiting": "À scorer", "flagged": "Signalé", "ranked": "Classé",
    },
    "en": {
        "title": "Pitch queue", "subtitle": "Intake, triage and review of incoming pitches",
        "disclaimer": "Triage aid only. Scores and selection do not replace investor review.",
        "language": "Interface language", "queue": "VC queue", "submit": "Submit a pitch",
        "all": "All sectors", "sector": "Sector", "search": "Search name or ID",
        "received": "Received", "scored": "Scored", "review_count": "Human review", "pending_count": "Pending",
        "priority": "Selected", "ranking": "Full ranking", "review": "Human review", "pending": "Unscored",
        "empty_scored": "No local V2 score is recorded yet. Submit a pitch or run the scoring pipeline to populate the queue.",
        "empty_selected": "No eligible pitch in this view.",
        "empty_review": "No flagged pitch in this view.",
        "empty_pending": "All visible pitches have usable scores.",
        "partial": "Selection uses the visible scored pitches and will change as the remaining pitches are processed.",
        "company": "Company", "score": "Score / 100", "recommendation": "Model opinion",
        "channel": "Channel", "status": "Status", "detail": "Pitch details", "choose": "Choose a pitch",
        "criterion": "Criterion", "corpus": "Corpus", "manual": "Manual submission",
        "reject": "Reject", "review_rec": "Review", "shortlist": "Shortlist",
        "criteria": "Criterion scores", "strengths": "Strengths", "risks": "Risks", "missing": "Missing information",
        "evidence": "Supporting excerpts", "text": "Pitch text", "no_score": "No model analysis for this pitch.",
        "guard": "This pitch is excluded from automatic ranking and requires human review.",
        "error": "Last scoring attempt:", "source_language": "Model comments appear in the language used for that run.",
        "manual_intro": "Enter a message, add PDFs or public links. Extracted text is screened before local scoring.",
        "name": "Company name", "sector_input": "Sector", "message": "Message or pitch text",
        "files": "PDF attachments", "links": "Public links (one per line)", "evaluate": "Extract and score locally",
        "processing": "Extracting and scoring locally…", "too_short": "Extracted text is too short to score (minimum 40 words).",
        "saved": "Pitch saved and scored.", "scoring_failed": "Pitch saved, but the model returned no usable score.",
        "source_report": "Source report", "waiting": "Awaiting score", "flagged": "Flagged", "ranked": "Ranked",
    },
}

